name: Update Version

on:
  pull_request:
    types: [closed]
    branches: [main]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  update-version:
    if: github.event.pull_request.merged && github.repositoryUrl == 'git://github.com/yextconsulting/pages-starter-react-consulting.git'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "17"
      - run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      - run: npm ci
      - name: Add commit hash to version.json for tracking.
        run: |
          HASH="$(git rev-parse HEAD)"

          jq --null-input \
            --arg version "$HASH" \
            '{"version": $version }' > version.json

          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git add version.json
          git commit -m "update version"
          git push

      - name: Tests ✅
        if: ${{ success() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "success",
            "description": "npm run build passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

      - name: Tests 🚨
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "failure",
            "description": "npm run build failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
